name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # Assurez-vous de choisir la version PHP appropriée pour votre projet

    - name: Install dependencies (if any)
      run: |
        composer install --no-progress --prefer-dist

    - name: Install Flyctl
      run: |
        curl -L https://fly.io/install.sh | sh
        echo "FLYCTL_INSTALL=\"$HOME/.fly\"" >> $GITHUB_ENV
        echo "PATH=\"$FLYCTL_INSTALL/bin:$PATH\"" >> $GITHUB_ENV

    - name: Deploy to Fly.io
      env:
        FLY_API_TOKEN:  ${{secrets.FLY_API_TOKEN }}
      run: |
        flyctl auth login --access-token $FLY_API_TOKEN
        flyctl deploy
